#include "DiggerModuleEditor.h"
#include "Modules/ModuleManager.h"
#include "EditorModeRegistry.h"
#include "DiggerEdMode.h"
#include "AssetToolsModule.h"
#include "DiggerEdModeToolkit.h"
#include "DiggerFeatureFlags.h"
#include "IAssetTools.h"
#include "Misc/ConfigCacheIni.h"
#include "Engine/CollisionProfile.h"
#include "Framework/Notifications/NotificationManager.h"
#include "Widgets/Notifications/SNotificationList.h"

// If you later use UCustomSDFBrushFactory
// #include "UCustomSDFBrushFactory.h"


#define LOCTEXT_NAMESPACE "FDiggerEditorModule"

void FDiggerEditorModule::StartupModule()
{
    // Load feature flags from Config/FeatureFlags.ini before anything else.
    // This controls which UI panels (Debug Flags, Developer Settings, etc.) are visible.
    FDiggerFeatureFlags::LoadFlagsFromPluginConfig();

    FEditorModeRegistry::Get().RegisterMode<FDiggerEdMode>(
        FDiggerEdMode::EM_DiggerEdModeId,
        LOCTEXT("DiggerEdModeName", "Digger Editor"),
        FSlateIcon(),
        true);



    // --- ROBUST CONFIG INJECTION START ---
    
    const FString SectionName = TEXT("/Script/Engine.CollisionProfile");
    const FString KeyName = TEXT("Profiles");
    const FString Filename = GEngineIni;
    
    // The exact string to inject
    FString ProfileString = TEXT("(Name=\"DiggerTraverser\",CollisionEnabled=QueryAndPhysics,bCanModify=True,ObjectTypeName=\"Pawn\",CustomResponses=(")
                            TEXT("(Channel=\"WorldStatic\",Response=ECR_Ignore),")   // Fall through Landscape
                            TEXT("(Channel=\"WorldDynamic\",Response=ECR_Block),")   // Walk on Tunnel
                            TEXT("(Channel=\"Pawn\",Response=ECR_Block),")           // Hit Players
                            TEXT("(Channel=\"Visibility\",Response=ECR_Block),")     // Line Traces hit me (Added)
                            TEXT("(Channel=\"Camera\",Response=ECR_Block),")         // Camera blocked by me (Added)
                            TEXT("(Channel=\"PhysicsBody\",Response=ECR_Block),")    // Hit Physics
                            TEXT("(Channel=\"Vehicle\",Response=ECR_Block),")        // Hit Cars
                            TEXT("(Channel=\"Destructible\",Response=ECR_Block)")    // Hit Breakables
                            TEXT("),HelpMessage=\"Auto-generated by Digger Plugin\")");
    

    if (GConfig)
    {
        // 1. Get the File object directly. 
        // This avoids the ambiguous "GetSection" return type error.
        FConfigFile* ConfigFile = GConfig->FindConfigFile(*Filename);

        if (ConfigFile)
        {
            // 2. Get the Section (Find or Create it).
            // This returns a direct reference to the TMultiMap.
            FConfigSection& Section = *ConfigFile->FindOrAddSection(*SectionName);

            // 3. Check for duplicates manually.
            // We look at all existing entries for "Profiles" to ensure we don't add ours twice.
            bool bFound = false;
            TArray<FConfigValue> Values;
            Section.MultiFind(FName(*KeyName), Values);

            for (const FConfigValue& Val : Values)
            {
                if (Val.GetValue() == ProfileString)
                {
                    bFound = true;
                    break;
                }
            }

            // 4. Inject if missing
            if (!bFound)
            {
                UE_LOG(LogTemp, Warning, TEXT("DiggerPlugin: Injecting DiggerTraverser profile..."));
                
                // Add the new line to the map
                Section.Add(FName(*KeyName), FConfigValue(ProfileString));

                // 5. Mark Dirty and Save
                ConfigFile->Dirty = true;
                GConfig->Flush(false, Filename);

                // 6. Reload Collision Manager
                UCollisionProfile::Get()->LoadProfileConfig(true);
            }
        }
    }
    // --- ROBUST CONFIG INJECTION END ---

    // Bind the Play Button Hook
    PreBeginPIEHandle = FEditorDelegates::PreBeginPIE.AddRaw(this, &FDiggerEditorModule::OnPreBeginPIE);
}

void FDiggerEditorModule::ShutdownModule()
{
    // Unbind to prevent crashes
    FEditorDelegates::PreBeginPIE.Remove(PreBeginPIEHandle);

    FEditorModeRegistry::Get().UnregisterMode(FDiggerEdMode::EM_DiggerEdModeId);
}

void FDiggerEditorModule::OnPreBeginPIE(bool bIsSimulating)
{
    // 1. Find the EDITOR WORLD Manager
    // We cannot use UGameplayStatics here because we are technically in the Editor context.
    UWorld* EditorWorld = GEditor ? GEditor->GetEditorWorldContext().World() : nullptr;
    ADiggerManager* EditMgr = ADiggerManager::FindDiggerManager(EditorWorld);

    if (!EditMgr || !EditMgr->HasVoxelData()) 
    {
        return;
    }

    const FText Title = FText::FromString("Digger");
    const FText Msg = FText::FromString("You have unsaved voxel sculpting data.\n\nYes: Save changes and enter Play mode (Recommended)\nNo: Discard changes and enter Play mode\nCancel: Stay in the editor");

    EAppReturnType::Type Result = FMessageDialog::Open(EAppMsgType::YesNoCancel, Msg, &Title);

    if (Result == EAppReturnType::Yes)
    {
        FString TargetFileName = TEXT("Default");

        // Try to find the Toolkit to get the user's typed name
        if (GLevelEditorModeTools().IsModeActive(FDiggerEdMode::EM_DiggerEdModeId))
        {
            FEdMode* Mode = GLevelEditorModeTools().GetActiveMode(FDiggerEdMode::EM_DiggerEdModeId);
            if (FDiggerEdMode* DiggerMode = static_cast<FDiggerEdMode*>(Mode))
            {
                if (auto Toolkit = DiggerMode->GetDiggerToolkit())
                {
                    TargetFileName = Toolkit->GetCurrentSaveFileName();
                }
            }
        }

        EditMgr->SaveAllChunks(TargetFileName);
        UE_LOG(LogTemp, Warning, TEXT("DiggerPlugin: Saved to '%s' before PIE."), *TargetFileName);
        
        EditMgr->ClearAllVoxelData();
    }
    else if (Result == EAppReturnType::No)
    {
        EditMgr->ClearAllVoxelData();
    }
    else // CANCEL
    {
        // 1. Show User Feedback IMMEDIATELY
        FNotificationInfo Info(FText::FromString("Aborting Play Session..."));
        Info.ExpireDuration = 3.0f;
        Info.bFireAndForget = true;
        Info.Image = FAppStyle::GetBrush("Icons.Warning"); // Optional icon
        FSlateNotificationManager::Get().AddNotification(Info);

        // Method 1: The official request
        GEditor->RequestEndPlayMap();

        // Method 2: The Timer (The reliable fallback)
        // We wait 0.1s to let the PIE world spin up just enough to receive the Kill command
        if (GEditor)
        {
            GEditor->GetTimerManager()->SetTimerForNextTick([]()
            {
                // Force stop
                GEditor->RequestEndPlayMap();
                
                // If using Simulate, sometimes this helps too:
                if (GEditor->PlayWorld)
                {
                    GEditor->EndPlayMap();
                }
            });
        }
    }
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FDiggerEditorModule, DiggerEditor)
